Collecting wandb
  Using cached wandb-0.19.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: click!=8.0.0,>=7.1 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (4.3.6)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (5.29.1)
Requirement already satisfied: psutil>=5.0.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (6.1.0)
Requirement already satisfied: pydantic<3,>=2.6 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (2.10.3)
Requirement already satisfied: pyyaml in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (2.19.2)
Requirement already satisfied: setproctitle in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (1.3.4)
Requirement already satisfied: setuptools in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (75.6.0)
Requirement already satisfied: typing-extensions<5,>=4.4 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from wandb) (4.12.2)
Requirement already satisfied: six>=1.4.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from docker-pycreds>=0.4.0->wandb) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.11)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb) (2.27.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2024.8.30)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/envs/chaos/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.1)
Using cached wandb-0.19.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.1 MB)
Installing collected packages: wandb
Successfully installed wandb-0.19.0
